MyHome.Web/Controllers/HouseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyHome.Domain;
using MyHome.Infrastructure;
using MyHome.Web.Models.House;

namespace MyHome.Web.Controllers
{
    [Authorize]
    public class HouseController : Controller
    {
        #region Private attributes
        private readonly MyHomeDbContext dbContext = null;
        #endregion

        #region Constructors
        /// <summary>
        /// Constructeur
        /// </summary>
        /// <param name="dbContext">Contexte de la base de données (l'instance nous sera transmise par injection)</param>
        public HouseController(MyHomeDbContext dbContext)
        {
            this.dbContext = dbContext;
        }
        #endregion

        public IActionResult Index()
        {
            // Sélection des maisons à afficher depuis la BDD
            // SELECT * FROM House 
            var houses = dbContext.Set<House>().ToList();

            // Remplissage du viewmodel avec le résultat de la requête précédente
            var vm = new ListHousesViewModel();
            vm.Houses.AddRange(houses);

            return View(vm);
        }

        [HttpGet] // facultatif car implicite
        public IActionResult Create()
        {
            // Retourne la vue (Create) avec une instance de CreateHouseViewModel afin de pouvoir l'utiliser sur la vue
            return View(new CreateHouseViewModel());
        }

        [HttpPost] 
        public IActionResult Create(CreateHouseViewModel vm)
        {
            // Sécurité : permet de s'assurer de la bonne saisie du formulaire par l'utilisateur
            if(ModelState.IsValid)
            {
                // Recherche d'une maison qui porte le même nom
                var existingHouse = dbContext
                    .Set<House>() // Equivalent SELECT * FROM House
                    .Where(x => x.Name == vm.Name) // Clause Where (équivalent where SQL)
                    .SingleOrDefault(); // 1 seul enregistrement ou null

                if (existingHouse == null)
                {
                    // Insertion de la maison en BDD
                    var newHouse = new House { Name = vm.Name };
                    dbContext.Add(newHouse); // Ajout de l'entité au contexte de données, il prends un Id temporaire
                    dbContext.SaveChanges(); // Application des changements en BDD (insert réel)

                    ViewBag.Success = $"La maison {vm.Name} a été créée avec succès";
                }
                else
                {
                    // On indique à l'utilisateur que la maison existe déjà, ViewBag == ViewData
                    ViewBag.Error = $"Une maison existe déjà pour le nom {vm.Name}";
                }
            }

            return View(vm);
        }

        /// <summary>
        /// Action de mise à jour de la fiche maison
        /// </summary>
        /// <param name="id">Identifiant de la maison à charger pour MAJ</param>
        /// <returns></returns>
        public IActionResult Edit(int id)
        {
            // Requêter en BDD la maison depuis son Id
            var existingHouse = dbContext
                .Set<House>()
                .Where(x => x.Id == id)
                .SingleOrDefault();

            var vm = new EditHouseViewModel();
            if(existingHouse == null)
            {
                // Stocker un message d'erreur
                ViewBag.Error = $"Aucune maison n'existe pour l'id {id}";
            }
            else
            {
                // Initialiser le viewmodel
                vm.Id = existingHouse.Id;
                vm.Name = existingHouse.Name;
            }
            
            // TODO ... Have fun!
            return View(vm);

        }

        /// <summary>
        /// Action de mise à jour de la maison
        /// </summary>
        /// <param name="id">Identifiant de la maison à mettre à jour</param>
        /// <param name="vm">Objet à jour</param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Edit(int id, EditHouseViewModel vm)
        {
            if (id == vm.Id)
            {
                var existingHouseByName = dbContext.Set<House>()
                    .Where(x => x.Name == vm.Name)
                    .SingleOrDefault();

                if (existingHouseByName == null)
                {
                    // Requêtage de l'entité à mettre à jour
                    var houseToUpdate = dbContext
                        .Set<House>()
                        .Where(x => x.Id == id)
                        .SingleOrDefault();

                    // Recopie des valeurs 
                    houseToUpdate.Name = vm.Name;
                    
                    // Mise à jour > UPDATE
                    dbContext.SaveChanges();

                    // Affichage du message de succès
                    ViewBag.Success = "Maison mise à jour avec succès";
                }
                else
                {
                    // Affichage du message d'erreur
                    ViewBag.Error = "Ce nom de maison existe déjà";
                }


            }
            else
                ViewBag.Error = "Incohérence entre Ids";

            return View(vm);
        }

    }
}

MyHome.Web/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyHome.Infrastructure;
using MyHome.Web.Models.Register;

namespace MyHome.Web.Controllers
{
    public class RegisterController : Controller
    {
        #region Private attributes

        private readonly MyHomeDbContext dbContext = null;
        #endregion
        
        /// <summary>
        /// Constructeur du controller
        /// </summary>
        /// <param name="myHomeDbContext">Contexte contenant la liaison avec la base de données</param>
        public RegisterController(MyHomeDbContext myHomeDbContext)
        {
            this.dbContext = myHomeDbContext;
        }

        public IActionResult Index()
        {
            return View(new RegisterViewModel());
        }

        public IActionResult Save(RegisterViewModel vm)
        {
            if(ModelState.IsValid)
            {
                // Traitement si la saisie utilisateur est valide
                // TODO : implémenter la sauvegarde
                Domain.User newUser = new Domain.User()
                {
                    Email = vm.Email,
                    FirstName = vm.FirstName,
                    LastName = vm.LastName,
                    Password = vm.Password
                };

                // Ajoute le nouvel objet au contexte de la base de données
                this.dbContext.Add(newUser);
                // Sauvegarde les modifications
                this.dbContext.SaveChanges();
            }
            else
            {
                // Traitement si la saisie utilisateur est invalide
            }
        

                //if(string.IsNullOrEmpty(vm.Email))
                //{
                //    ViewData["error"] = "L'email est obligatoire";
                //}

                //if (string.IsNullOrEmpty(vm.FirstName))
                //{
                //    ViewData["error"] = ViewData["error"] + " Le prénom est obligatoire";
                //}

                
                return View();
        }
    }
}

MyHome.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyHome.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">MyHome.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a asp-area="" asp-controller="House" asp-action="Index">Mes maisons</a></li>
                        <li><a asp-area="" asp-controller="Account" asp-action="Logout">Déconnexion</a></li>
                    }
                    else
                    {
                        <li><a asp-area="" asp-controller="Register" asp-action="Index">Inscription</a></li>
                        <li><a asp-area="" asp-controller="Account" asp-action="Login">Connexion</a></li>
                    }

                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @if (!string.IsNullOrEmpty(ViewBag.Success))
        {
            <div class="alert alert-success alert-dismissable" >
                <p>@ViewBag.Success</p>
            </div>
        }

        @if (!string.IsNullOrEmpty(ViewBag.Error))
        {
            <div class="alert alert-danger alert-dismissable">
                <p>@ViewBag.Error</p>
            </div>
        }

        @if (User.Identity.IsAuthenticated)
        {
            // Affichage du prénom de l'utilisateur
            <p>Bonjour @User.Identity.Name</p>
        }

        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - MyHome.Web</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <!-- Lib qui permet de faire de la validation de formulaires automatiquement -->
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>